### PR TITLE
Additional definitions from HRRR

### PR DESCRIPTION
**Pull request by rustyconover**
So I spent some time and wrote a program to automatically generate the local definitions from HRRR file I had locally.

I tried to match your examples exactly, but I didn't know if you preferred tabs or spaces for indentations.

I'll be publishing a repo with the tool that did this for me in case you find it useful.

### CODE REVIEW

**Comment by rustyconover** [comment]
You can see the tool that generated these files here:

https://github.com/rustyconover/ncep-grib2-definitions

**Comment by weech** [comment]
The first commit looks mostly good. The second one though adds a bunch of codes that are already in the ecCodes package. Were you having issues with those or did you add them preemptively? For example, `discipline` 0, `parameterCategory` 16, `parameterNumber` 196 [already has an entry](https://github.com/ecmwf/eccodes/blob/8337591d5131f08e9b0e187080faebf7acbb9009/definitions/grib2/localConcepts/kwbc/name.def#L1041).

**Comment by rustyconover** [comment]
I was having issues where the "name" field was returning unknown and based on that I told the program to get the codes.

Maybe that's not a good way to decide what should be included and what shouldn't.

**Comment by rustyconover** [comment]
I'm now seeing an example where:

`Dict{String,Any}("units" => "%","name" => "Relative humidity","typeOfLevel" => "unknown","level" => 0)`

The "typeOfLevel" field is unknown.

Do you know what could be causing that?

**Comment by weech** [comment]
The best way to decide what to include is to add definitions for whatever is giving "unknown" values, that's why I asked :)  
The details of how ecCodes definition system works are arcane, and I wouldn't be surprised if there are weird corner cases.

That missing "typeOfLevel" means that the ecCodes developers never came up with a short name for that level. I don't know why since running `grib_dump` on the file shows that it knows that the level kind is supposed to be "Highest tropospheric freezing level", but for some reason they never put it in [the list of "typeOfLevel" values](https://github.com/ecmwf/eccodes/blob/master/definitions/grib2/typeOfLevelConcept.def). It looks like that is customizable though, so I'll find the right place and create a definition file for it (and call it highestTropoFreezingLevel).

I'm going to go ahead and merge the pull request.

**Comment by weech** [comment]
Actually the typeOfLevel field is not currently overrideable for GRIB2. That's unfortunate because it looks like it was for GRIB1. The nameOfFirstFixedSurface field should give you the correct name in most cases. You could have the expression `msg["typeOfLevel"] != "unknown" ? msg["typeOfLevel"] : msg["nameOfFirstFixedSurface"]`. That fills in most of the gaps but not all of them.

**Pull request merged**
